version: '3.3'
services:
  elasticsearch:
    image: jbarlow83/ocrmypdf-alpine:latest
    container_name: ocrmypdf
    privileged: true
    ports:
      - 5000:5000
      - 8501:8501

#http://127.0.0.1:5000
