version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Admin123
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=Users123
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"