---
services:
  msedge:
    image: lscr.io/linuxserver/msedge:latest
    container_name: msedge
    #restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - EDGE_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ./config:/config:rw
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"