version: '3.9'
services:
  teamide:
    image: teamide/teamide-server:latest
    container_name: teamide
    privileged: true
    #restart: always
    volumes:
      - './data:/opt/teamide/data'
    ports:
      - '21080:21080'

# http://127.0.0.1  teamadmin/teamadmin